import Foundation

/// The request bodies the log sheets send, and the date policy that decides which of them
/// a chosen day will accept.
///
/// Both halves are here together because they are the same contract read from two ends:
/// `checkDatePolicy` in `api/src/index.ts` decides what the server will take, and
/// `EvaLogAvailability` decides what the picker offers. #160 asks for the second to be
/// *visible* rather than discovered — a type the server would refuse has to look
/// unavailable before it is tapped, not answer `FUTURE_DATE_NOT_ALLOWED` after.

// MARK: - The envelope

/// `POST /me/events` and `PATCH /me/events/{id}`.
///
/// `loggedAt` is deliberately **not** here. The route computes it from `timeZone` — the
/// current time on a day that is today, midday on any other — and that is a better answer
/// than one the client builds, because it is the same answer for every device. On a
/// `PATCH` its absence is also what preserves it: an edit must not move an entry's place
/// in the day's list.
struct EvaEventWrite: Encodable, Hashable, Sendable {

    let payload: EvaEventPayload
    /// The day the user chose, never a device clock.
    let localDate: EvaDay
    /// Trimmed, or `nil` for no note.
    let note: String?
    /// The device's zone, so the server's "today" is the user's today.
    ///
    /// Sending it is not optional in any useful sense: without it the route assumes UTC
    /// and allows a day of slack either side, so the server's idea of what is in the
    /// future stops matching the grid's — and the picker would offer a day the server
    /// then refuses, or refuse one it would have taken.
    let timeZone: String
    /// Generated by the device, per draft. The route returns the event a repeated key
    /// already created rather than writing a second one, so a retry after a timeout
    /// cannot log the same run twice. Ignored for the one-per-day types, which dedupe on
    /// the day itself.
    let idempotencyKey: String

    init(
        payload: EvaEventPayload,
        localDate: EvaDay,
        note: String? = nil,
        idempotencyKey: String,
        timeZone: String = TimeZone.current.identifier
    ) {
        self.payload = payload
        self.localDate = localDate
        self.note = note
        self.timeZone = timeZone
        self.idempotencyKey = idempotencyKey
    }

    var type: EvaEventType { payload.type }

    func encode(to encoder: any Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(payload.type, forKey: .type)
        try container.encode(localDate.isoDate, forKey: .localDate)
        try container.encode(timeZone, forKey: .timeZone)
        try container.encode(idempotencyKey, forKey: .idempotencyKey)
        // Omitted rather than null when there is none, which is what the route stores
        // either way. A note that is only whitespace never reaches here — the drafts trim.
        try container.encodeIfPresent(note, forKey: .note)
        try container.encode(payload, forKey: .payload)
    }

    private enum CodingKeys: String, CodingKey {
        case type, localDate, timeZone, idempotencyKey, note, payload
    }
}

/// `PUT /me/body-signals/{date}` — the one-per-day upsert.
///
/// The same information as an `EvaEventWrite` carrying `.bodySignals`, in the shape that
/// route wants: the ratings sit at the **top level**, because the path already says what
/// this is. It exists alongside the generic write rather than instead of it because it is
/// the route designed for this: the day is the address, so a device that has never seen
/// the day's existing entry can still replace it without first asking for its id.
struct EvaBodySignalsWrite: Encodable, Hashable, Sendable {

    let payload: EvaBodySignalsPayload
    let localDate: EvaDay
    let note: String?
    let timeZone: String
    let idempotencyKey: String

    init(
        payload: EvaBodySignalsPayload,
        localDate: EvaDay,
        note: String? = nil,
        idempotencyKey: String,
        timeZone: String = TimeZone.current.identifier
    ) {
        self.payload = payload
        self.localDate = localDate
        self.note = note
        self.timeZone = timeZone
        self.idempotencyKey = idempotencyKey
    }

    func encode(to encoder: any Encoder) throws {
        // The payload's own keys, flattened into the envelope — one encoder, two
        // contributors, which is what "at the top level" means on the wire.
        try payload.encode(to: encoder)
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(timeZone, forKey: .timeZone)
        try container.encode(idempotencyKey, forKey: .idempotencyKey)
        try container.encodeIfPresent(note, forKey: .note)
    }

    private enum CodingKeys: String, CodingKey { case timeZone, idempotencyKey, note }
}

// MARK: - What a day will take

/// Whether one type can be logged on one day, and why not when it cannot.
///
/// A reason rather than a `Bool`, because #160's criterion is that an unavailable option
/// is **visibly** unavailable: the picker draws the sentence, so the sentence has to exist
/// before the row is drawn.
enum EvaLogAvailability: Hashable, Sendable {
    case available
    /// Past today, and this is not an appointment. `FUTURE_DATE_NOT_ALLOWED`.
    case futureDay
    /// Further back than the API will accept. `BACKDATE_LIMIT_EXCEEDED`.
    case tooFarBack
    /// Reserved in the model and refused by the route until C10 ships it with its privacy
    /// switch. Not a property of the day.
    case notYetAvailable

    var isAvailable: Bool { self == .available }

    /// What the picker says under the row. The API's own wording, in the second person —
    /// these are the sentences the server would have answered with, said before the tap
    /// instead of after it.
    var reason: String? {
        switch self {
        case .available: nil
        case .futureDay: "Only appointments can be logged ahead"
        case .tooFarBack:
            "Entries can be backdated up to \(EvaEventType.backdateLimitMonths) months"
        case .notYetAvailable: "Not available yet"
        }
    }
}

extension EvaEventType {

    /// How far back the API will accept an entry — `minusTwelveMonths` in
    /// `api/src/index.ts` (PRD edge case 1).
    static let backdateLimitMonths = 12

    /// Whether this type can be logged on `day`.
    ///
    /// Future days take appointments and nothing else: you cannot observe a flow, a body
    /// signal or a workout that has not happened. `today` is passed in rather than read
    /// here so the rule is the same value the grid is drawing against — and so it can be
    /// asked about a day either side of midnight in a test.
    func availability(on day: EvaDay, today: EvaDay) -> EvaLogAvailability {
        guard self != .sex else { return .notYetAvailable }
        // `latest` on the server is today exactly, because every write from here carries a
        // `timeZone` and the slack day is only granted to callers that do not.
        if day > today, self != .appointment { return .futureDay }
        return day < Self.backdateFloor(from: today) ? .tooFarBack : .available
    }

    /// The earliest day the API will accept, given what day it is.
    ///
    /// The same day one year earlier — `minusTwelveMonths`. Written without normalising
    /// the one day that does not exist (29 February in a common year), because
    /// `EvaDay`'s ordering makes an impossible floor behave identically to the server's
    /// normalised 1 March: every *real* day lands on the same side of both.
    static func backdateFloor(from today: EvaDay) -> EvaDay {
        EvaDay(year: today.year - 1, month: today.month, day: today.day)
    }
}
