import type { Confidence, Slot } from './content'

/**
 * The Today card's rules layer (#96, slice D1 of #10): a day's inputs in, a *subject* out.
 *
 * PRD §Dashboard, Other requirements 1: "The Today card is generated by a rules layer that
 * selects the message and its inputs, with the model used for phrasing only. The message
 * subject is never free-generated." This module is that layer and the only place a ladder
 * rung is chosen. D3 (#98) fills the template this names and caches the result; D9 (#106)
 * rephrases what D3 filled. Neither may pick a different subject.
 *
 * **Pure, and that is the design rather than a property of it.** Nothing here reads
 * Firestore, a clock or the network — `now` is an argument like everything else. The cycle
 * maths (C11, #11) and the red-flag mapping (D10) arrive as *inputs*, so the ladder can be
 * exercised against fixtures for states no real account has reached, and so it breaks at
 * the seam rather than inside the ladder when C11's interface moves.
 *
 * **It contains no text.** The output names a template id; `content.ts` (D2, #97) holds the
 * words that id resolves to, under a reviewer's name. The one import is `import type`,
 * erased at compile time (`verbatimModuleSyntax`), so ARCHITECTURE §3's layering is
 * untouched: the vocabulary is shared, the module is not. Sharing `Slot` rather than
 * restating it is what makes "no comparison to other users, no scores for the person, no
 * streaks" structural — `SubjectSlots` cannot carry a key `SLOTS` does not have, so adding
 * a score or a streak would need a change in `content.ts`, a review, and this file.
 *
 * **What it deliberately does not decide.** Rung 2's thresholds (A32, #26) arrive as
 * configuration and this module refuses to answer without them; the ≥3-cycle gate and the
 * irregularity band are C11's constants and arrive as the answers C11 already reached, so
 * no number here can drift from the one the fertile window uses. Nudge eligibility is D6,
 * banner selection D7, and the mode-specific rungs 1 and 3 are D10.
 */

/** Which mode the Dashboard is in (PRD §Dashboard, Mode variants). Only `cycle` has rules
 *  here; the rest are D10's and fall through to the educational rung rather than borrowing
 *  cycle content, because the wrong mode's card is worse than a generic one. */
export type Mode = 'cycle' | 'planning' | 'pregnancy' | 'postpartum' | 'loss'

/**
 * The ladder rung a subject came from — the vocabulary `content.ts`'s `Template.rung`
 * already uses, so D3 can check that the template it loaded belongs to the rung this
 * chose.
 *
 * Six of these are the PRD's ladder, in its order. `setup` is not a rung: it is the
 * cold-start card (PRD Edge case 1), decided inside the phase rung because "no phase,
 * because there is no data" is the phase rung's answer when there is nothing to say.
 */
export type Rung = 'flag' | 'pattern' | 'milestone' | 'phase' | 'nutrition' | 'education' | 'setup'

/**
 * The template ids this ladder can name, with the canvas state each renders.
 *
 * Ids, not words: `content.ts` says an id is permanent and opaque, so these are safe to
 * hold in code while every string behind them stays a Firestore document that a clinician
 * signed. The canvas state is in the comment because the acceptance criteria — and the
 * design review — are written in those terms.
 */
export const TEMPLATE = {
  /** `home_flag` — the red-flag escalation card. D10 owns what triggers it. */
  redFlag: 'red_flag',
  /** `home_h` — a pattern in her own logged data, named and pointed outward. */
  moodPattern: 'mood_pattern',
  /** `home_f` — the period is later than predicted; no speculation about why. */
  latePeriod: 'late_period',
  /** `home_e` — she logged signals, and they lead over what the phase predicts. */
  signalOverridesPhase: 'signal_overrides_phase',
  /** `home_g` — she logged signals and there is no cycle data; no phase is mentioned. */
  signalsToday: 'signals_today',
  /** `home_d` — phase context, hedged. */
  phaseEnergy: 'phase_energy',
  /** `home_b` — too few counted cycles to estimate a phase; says what is needed. */
  stillLearning: 'still_learning',
  /** `home_c` — irregular, so no phase is estimated at all. */
  irregular: 'irregular',
  /** `home_a` — nothing logged yet; explains what to log first. */
  coldStart: 'cold_start',
  /** `home_edu` — the fallback, labelled as a read rather than as insight. */
  educational: 'educational',
} as const

export type TemplateId = (typeof TEMPLATE)[keyof typeof TEMPLATE]

/** Slot values the card may carry: cycle day, a count, dates and times, a phase code.
 *  Typed against `content.ts`'s `Slot` so the vocabulary has exactly one definition. */
export type SubjectSlots = Partial<Record<Slot, string | number>>

/** What this module answers with: a rung, a template id, the values that template's slots
 *  take, and how confidently the card may speak. No prose, no score, no streak. */
export interface Subject {
  rung: Rung
  templateId: TemplateId
  slots: SubjectSlots
  confidence: Confidence
}

// ── C11's interface (#11), as this module consumes it ──────────────────────────────────
// A fixture until C11 exists and #26 answers A11's routed constants. The *shape* is
// settled here; none of the arithmetic behind it is, and none of it is re-derived here.

/** The phase words the PRD and the canvas already use ("Cycle day 15 · likely follicular";
 *  "luteal surfaces bloating and cravings, menstrual surfaces cramps"). C11 owns which one
 *  a day falls in; this module passes it to the `phase` slot, and branches on it in exactly
 *  one place — rung 4, which selects its only card for the one phase that card is true of
 *  (#184). */
export type PhaseCode = 'menstrual' | 'follicular' | 'ovulation' | 'luteal'

/**
 * How tightly C11 holds an estimate (A27): `none` is withheld, `wide` is the 3–5-cycle
 * band, `narrow` the 6-or-more band. A band, never a percentage — PRD Confidence and cold
 * start 1 asks for honest wording, not a number the user has to interpret.
 */
export type PhaseConfidence = 'none' | 'wide' | 'narrow'

export interface PhaseEstimate {
  code: PhaseCode
  confidence: PhaseConfidence
}

/**
 * Why C11 will not estimate from her cycle lengths — and, when it will not, **which fact
 * that is** (#190).
 *
 * It was a boolean, and the boolean conflated two things that are not the same fact:
 *
 *  - `cycles-vary` — the spread is in the cycles Eva *counted*, or in a repeated run of
 *    intervals outside the countable range. Something about her body: FIGO's own AUB
 *    System 1, the source behind the bands, calls a cycle of 38 days or more infrequent
 *    menstruation, and more than one of them is that pattern rather than a stray.
 *  - `uncountable-cycle` — one single interval in the window fell outside the countable
 *    range, and her counted cycles agree with each other inside her band. Something about
 *    the *data*, not about her: Eva cannot read that interval and says so.
 *
 * **Only the first may be stated as a fact about her cycles**, which is the whole of #190's
 * second half. `home_c` reads "Your recent cycle lengths vary significantly"; a woman whose
 * cycles are all 28 days and who missed one period start was shown it for six cycles, and
 * the sentence was false every day of them. The type is a union rather than a second boolean
 * beside the first so that a card cannot be selected off "irregular" again without the
 * compiler asking which of the two it means.
 *
 * Both still withhold the prediction and both still withhold the phase — this names the
 * reason, it does not reopen a gate. See `analyzeCycles` for where the two are told apart.
 */
export type Irregularity = 'none' | 'cycles-vary' | 'uncountable-cycle'

export interface CycleEstimate {
  /** Counted cycles C11 holds (A25: first flow day to first flow day, 21–45 days). Stated
   *  on the card as a fact, never as progress toward a goal — PRD tone rule 4. */
  countedCycles: number
  /**
   * C11's own answer to "do I have enough cycles to estimate from" (PRD Confidence and
   * cold start 2, the ≥3 gate). The **answer**, not the number: A11 routed that constant to
   * #26 and C11 reads it from configuration, so re-deciding it here would be a second
   * threshold that could drift from the one the calendar draws.
   */
  enoughCyclesForEstimates: boolean
  /** C11's irregularity answer (A25's FIGO band). PRD Confidence and cold start 3 says the
   *  card matches "the rule used for the fertile window" — so this is that same answer, and
   *  there is deliberately no second test of variation anywhere in this file. **Not a
   *  boolean** (#190): anything but `none` withholds the phase, and only `cycles-vary` may
   *  be spoken as a fact about her cycles. See `Irregularity`. */
  irregularity: Irregularity
  /** Today's cycle day, counted from the current cycle's first flow day (A25 item 6).
   *  `null` when no flow day has been logged, which is what "no cycle data" means here. */
  cycleDay: number | null
  /** The estimated phase, or `null` when C11 withheld one. A non-null estimate is still
   *  gated below: `confidence: 'none'` never reaches a card. */
  phase: PhaseEstimate | null
  /**
   * Whole days since the predicted first flow day passed — `1` on the day after it — or
   * `null` when there is no prediction. A count, not a judgement: whether a prediction
   * exists at all is C11's gate, so lateness carries no threshold of its own here.
   *
   * **`0` is the predicted day itself, and is not late.** It arrives as `0` rather than as
   * `null` because "the prediction is today" and "there is no prediction" are different
   * facts; the rung below is where that distinction is spent.
   */
  daysPastPredictedPeriod: number | null
}

// ── The day's inputs ───────────────────────────────────────────────────────────────────

export interface LoggedSymptom {
  /** A `refdata/` symptom code (#24). Never a label — the words are the client's. */
  code: string
  severity: 'normal' | 'severe'
}

/**
 * One `bodySignals` entry, as this module needs it.
 *
 * **This is the only logged-data input, and it is body signals only.** There is no event
 * list and no event type here, so a Sex entry cannot reach the card by any path — PRD Edge
 * case 6 ("Sex event type hidden in Settings — no dashboard content may reference it")
 * needs no branch, because hiding something the rules layer never receives changes nothing.
 * Adding one would be a change to this interface, which is where it should be argued.
 */
export interface SignalEntry {
  /** The user's local date, `YYYY-MM-DD`. What "consecutive days" counts. */
  localDate: string
  /** ISO-8601 **with an offset** (`…Z` or `…+02:00`). What "in the last 24 hours" measures,
   *  and why it is not the event's wall-clock string: a pure function cannot resolve a wall
   *  clock without the process timezone, and a rules layer that answered differently on a
   *  server in another region would be unfalsifiable. D3 converts, using the request's
   *  `timeZone` exactly as `events.ts` describes. */
  loggedAt: string
  /** 1–5, or `null` for "not answered" — which `events.ts` is careful is not a 3. */
  energy: number | null
  mood: number | null
  sleep: number | null
  symptoms: readonly LoggedSymptom[]
}

/**
 * Rung 1's trigger, already resolved (PRD §Calendar Other requirements 5: a red flag is
 * deterministic and bypasses the model). D1 owns the rung, its precedence and this shape;
 * **D10 owns the mapping** from a logged code to a flag, because that mapping is clinical
 * and belongs with #26's red-flag triggers rather than in a ladder.
 */
export interface RedFlagSignal {
  code: string
  /** The `loggedAt` slot the escalation card carries. Same frame as `SignalEntry.loggedAt`. */
  loggedAt: string
}

/** An appointment ahead of `today` — rung 3's input. */
export interface UpcomingAppointment {
  /** Local wall clock `YYYY-MM-DDTHH:mm:ss`, as `events.ts` stores it. */
  startAt: string
  /** A `refdata/` appointment-type code, or `null`. */
  type: string | null
  /** Whole days from `today`: `0` today, `1` tomorrow. Computed by the caller, which is
   *  the only place that knows the user's timezone. */
  inDays: number
}

/** Today's totals against today's targets, for rung 5 (#25 S3/S4). Values, never scores —
 *  PRD Today at a glance 3, and the reason none of these is ever a slot. */
export interface NutritionTotals {
  caloriesRemaining: number
  proteinG: number
  waterMl: number
  activityMin: number
}

export interface DashboardInput {
  mode: Mode
  /** The user's local date this card is for, `YYYY-MM-DD`. */
  today: string
  /** The instant the card is generated, ISO-8601 with an offset. Passed in because this
   *  module reads no clock: the same inputs must produce the same card in a test, in D3
   *  and on a replay. */
  now: string
  cycle: CycleEstimate
  /** The body-signal entries D3 fetched, in any order. It must cover at least the days
   *  rung 2's rule spans; entries outside the windows below are ignored, not an error. */
  signals: readonly SignalEntry[]
  /** Rung 1. `null` in every mode until D10 supplies the mapping — there is nothing to
   *  resolve here, so nothing here can get it wrong. */
  redFlag: RedFlagSignal | null
  /** Rung 3's input. Read by the milestone rung, which has no cycle-mode template to
   *  select — see there. */
  upcomingAppointments: readonly UpcomingAppointment[]
  /** Whether the profile carries what a personalised suggestion would need (#19). Rung 5's
   *  gate, with `nutritionSetUp`: PRD Confidence and cold start 4 — "the card must never
   *  generate a personalised-sounding message from data the app does not have". */
  profileComplete: boolean
  /** Whether the Nutrition adviser setup is complete (#25). */
  nutritionSetUp: boolean
  /** Present only when `nutritionSetUp` — PRD Today at a glance 2 refuses a partial state. */
  todayTotals: NutritionTotals | null
  /**
   * Days since the last log of any kind; `null` when nothing has ever been logged, which
   * is how the cold-start card knows it is the first open.
   *
   * **An input, never an output.** PRD tone rule 4 bans streaks, and the logging gap is the
   * number a streak would be built from; it feeds the nudge slot (D6), which states gaps
   * neutrally, and it never becomes a slot. `Slot` has no key for it, so it cannot.
   */
  daysSinceLastLog: number | null
}

// ── Rung 2's configuration (A32, #26) ──────────────────────────────────────────────────

/**
 * The shape of "a pattern in her own logged data that is worth naming" — A32's rule, with
 * every number left out.
 *
 * A32 settled the rule's *form* (PR #109): three consecutive logged days with mood, energy
 * or sleep at 2 of 5 or below, or the same symptom marked severe on three consecutive days,
 * and a card that names the pattern and points outward. It is still "a product heuristic,
 * stated as one; not a clinical instrument", so the doses stay configuration and this file
 * holds none of them. A plausible default written here would be a rule that looks live and
 * is not, which is the thing #26's process note exists to prevent.
 *
 * **Which signals count is not configurable, and must not become so**, because it is the
 * card's own sentences: `mood_pattern` says "You've logged low mood for three consecutive
 * days" and "Sleep has also been below your usual level during the same period". A rule
 * that could be pointed at energy would make the card describe something she did not log.
 * That is a narrower reading than the sentence above, and it is A32's own: A32's record
 * ends "The canvas' `home_h` copy is the shape", and that copy names mood and sleep
 * together and never mentions energy. Resolving the two statements toward the copy is a
 * reading of the decision, not a judgement call over it.
 */
export interface PatternRule {
  /** Consecutive logged days carrying **both** a low mood and a low sleep rating. */
  lowSignalDays: number
  /**
   * The rating at or below which mood and sleep each count as low.
   *
   * Ratings are whole numbers from 1 to 5 (`parseRating`, `index.ts`), so the usable range
   * is **1–4**: at 5 every answered rating is low, and the rule matches anyone who logs
   * anything three days running. `requirePatternRule` refuses it.
   */
  lowAtOrBelow: number
  /**
   * Consecutive logged days carrying the *same* symptom marked severe — A32's second arm,
   * **dosed but not selectable in v1**.
   *
   * `content/` has no `symptom_pattern` template for it to name, and the one pattern card
   * describes low mood and sleep — so selecting that card for a severe-symptom run would
   * tell her she logged something she did not. D2 owns writing the card; until it exists
   * this number is validated and unused, and such a run falls through to `signals_today`.
   *
   * **That fallback is not a true card either, and this comment used to say it was** (#177).
   * `signals_today` reads "You logged low energy and a headache today", which a severe-cramps
   * run did not. The canvas has not drawn the variant; `api/test/dashboard-copy.test.ts`
   * records the mismatch and the PR that added it asks for the card. Nothing here changes
   * until that card exists — the routing is right, the words behind it are what is missing.
   */
  severeSymptomDays: number
}

/** Everything about this ladder that is configured rather than coded. One member today;
 *  it is an object so that adding the next one is not a signature change for every caller. */
export interface DashboardRules {
  /** `null` until #26's rule is loaded. Reaching rung 2 with it unset throws. */
  pattern: PatternRule | null
}

/** Thrown when rung 2 is reached and its rule is missing or unusable. Its own class so a
 *  caller can tell a missing configuration from a bug, and so the refusal is greppable. */
export class PatternRuleUnsetError extends Error {
  constructor(reason = 'no rule is configured') {
    super(`the Today card's pattern rung cannot be evaluated: ${reason}`)
    this.name = 'PatternRuleUnsetError'
  }
}

/**
 * Thrown when a time input is not the shape this module documents: an instant with an
 * offset for `now` and `loggedAt`, a `YYYY-MM-DD` calendar date for `today`.
 *
 * Loud rather than lenient, in both directions. An unparseable `loggedAt` read as "nothing
 * logged" would silently drop the user's own report, which is the one failure the card's
 * central rule exists to prevent; a malformed `today` would make rung 2's run match
 * nothing, which is a rule that looks live and is not. Carries the field name and the shape
 * expected — never the value (GUARDRAILS 12).
 */
export class InvalidTimeError extends Error {
  constructor(field: string, expected: string) {
    super(`the Today card's ${field} must be ${expected}`)
    this.name = 'InvalidTimeError'
  }
}

// ── Helpers ────────────────────────────────────────────────────────────────────────────

/** PRD §Dashboard: "If the user has logged body signals in the last 24 hours…". The
 *  window is the PRD's, written once. */
const OBSERVED_WINDOW_MS = 24 * 60 * 60 * 1000

const OFFSET = /(?:Z|[+-]\d{2}:?\d{2})$/

const instant = (value: string, field: string): number => {
  const parsed = OFFSET.test(value) ? Date.parse(value) : Number.NaN
  if (Number.isNaN(parsed)) throw new InvalidTimeError(field, 'ISO-8601 with an offset')
  return parsed
}

const LOCAL_DATE = /^\d{4}-\d{2}-\d{2}$/

/** `YYYY-MM-DD` shifted by whole days, in UTC so the arithmetic cannot pick up the
 *  process timezone. Local dates are calendar labels here, not instants. */
const shiftDays = (localDate: string, field: string, delta: number): string => {
  const [year, month, day] = localDate.split('-').map(Number)
  if (!LOCAL_DATE.test(localDate) || year === undefined || month === undefined || day === undefined) {
    throw new InvalidTimeError(field, 'a YYYY-MM-DD calendar date')
  }
  const at = Date.UTC(year, month - 1, day)
  // The shape check is not enough: `Date.UTC` *rolls over* rather than refusing, so
  // `2026-13-45` becomes `2027-02-14` and the run below would search days nothing can
  // carry — a rule that looks live and is not, which is what this error exists to prevent.
  // The round trip is the only check that catches it, and it catches a two-digit year too.
  if (Number.isNaN(at) || new Date(at).toISOString().slice(0, 10) !== localDate) {
    throw new InvalidTimeError(field, 'a real YYYY-MM-DD calendar date')
  }
  return new Date(at + delta * 86_400_000).toISOString().slice(0, 10)
}

/** An entry with no rating and no symptom is a day she opened the sheet, not a day she
 *  reported something. Nothing selects a card from it. */
const hasSignal = (entry: SignalEntry): boolean =>
  entry.energy !== null || entry.mood !== null || entry.sleep !== null || entry.symptoms.length > 0

/**
 * The most recent entry she actually reported something in, inside the observed window.
 *
 * **The calendar date is checked before the instant is parsed**, and that order is the
 * point. A 24-hour window ending on `today` can only touch `today` and the day either side
 * of it, whatever the offset — so an entry from last week is skipped without `loggedAt`
 * being read at all. Parsing it first meant one malformed stored row the ladder would have
 * ignored threw for the whole card, and `GET /me/today` then failed for that user every day
 * until the row was fixed. A malformed instant on a day the window *does* cover still
 * throws: there, reading it as "nothing logged" would drop her own report.
 */
const observedSignal = (input: DashboardInput): SignalEntry | null => {
  const now = instant(input.now, 'now')
  const reachable = new Set([
    shiftDays(input.today, 'today', -1),
    input.today,
    shiftDays(input.today, 'today', 1),
  ])
  let latest: SignalEntry | null = null
  let latestAt = Number.NEGATIVE_INFINITY
  for (const entry of input.signals) {
    if (!hasSignal(entry) || !reachable.has(entry.localDate)) continue
    const at = instant(entry.loggedAt, 'loggedAt')
    if (at > now || now - at > OBSERVED_WINDOW_MS) continue
    if (at > latestAt) {
      latestAt = at
      latest = entry
    }
  }
  return latest
}

/**
 * The phase, if it may be spoken at all.
 *
 * Three gates, and all three are C11's own answers rather than tests invented here: enough
 * counted cycles, not irregular, and an estimate C11 did not withhold. The third is
 * belt-and-braces on purpose — a `confidence: 'none'` estimate must select a no-phase
 * subject, never a hedged phase, and that has to hold even if C11 one day hands one over.
 */
const speakablePhase = (
  cycle: CycleEstimate,
): { code: PhaseCode; confidence: Exclude<PhaseConfidence, 'none'> } | null => {
  // `!== 'none'` rather than a named arm: **every** reason C11 withholds for withholds the
  // phase too, so a reason added to `Irregularity` later suppresses by default rather than
  // by somebody remembering to extend this line (#190).
  if (!cycle.enoughCyclesForEstimates || cycle.irregularity !== 'none') return null
  if (cycle.phase === null || cycle.phase.confidence === 'none') return null
  if (cycle.cycleDay === null) return null
  return { code: cycle.phase.code, confidence: cycle.phase.confidence }
}

/**
 * C11's band → the card's wording class.
 *
 * Both bands hedge, because v1 has **no confirmed-ovulation path**: A26 derives ovulation
 * from the fixed-luteal calendar convention rather than observing it, so "likely" is the
 * honest word at every band (PRD Confidence and cold start 1, and the seed's phase
 * templates, which are all `hedged`). If C11 ever gains a confirmed band, this table is the
 * one place that changes — which is why it is a table and not a constant.
 */
const PHASE_WORDING = {
  wide: 'hedged',
  narrow: 'hedged',
} as const satisfies Record<Exclude<PhaseConfidence, 'none'>, Confidence>

// ── Rung 2's rule ──────────────────────────────────────────────────────────────────────

/** The `days` calendar days ending on `today`, each carrying a reported entry — or `null`
 *  if any of them is missing. "Consecutive" is calendar-consecutive and includes today:
 *  rung 2's example is "a third consecutive day of low mood", so today is the third, and a
 *  run that ended last week is not today's news. */
const runEndingToday = (input: DashboardInput, days: number): SignalEntry[] | null => {
  const run: SignalEntry[] = []
  for (let back = 0; back < days; back += 1) {
    const date = shiftDays(input.today, 'today', -back)
    const entry = input.signals.find(
      (candidate) => candidate.localDate === date && hasSignal(candidate),
    )
    if (!entry) return null
    run.push(entry)
  }
  return run
}

/**
 * A day the pattern card's words are true of.
 *
 * **Mood and sleep, both, and both answered** — because that is what `mood_pattern` says:
 * "You've logged low mood for three consecutive days", and "Sleep has also been below your
 * usual level during the same period". The canvas carries that second sentence verbatim, so
 * it is the specification rather than loose copy around a wider rule.
 *
 * Two narrowings from what this was, and each closes a way the card could lie about her own
 * data — the one thing this product cannot get wrong. It was `.some()` over energy, mood and
 * sleep: three days of low *energy* with mood 5 and sleep 5 produced the card, and `.some()`
 * did not even require the three days to agree on which signal was low. **Energy is not in
 * the predicate at all**, because no card mentions it.
 *
 * The honest cost: this fires rarely. It needs both signals present and low on every day of
 * the run, so most days fall through to the educational card instead — which is the right
 * trade at v1. A rare true card beats a frequent false one, and the fallback is not a bad
 * experience. When D2 writes a single-signal card, the predicate widens to meet it.
 */
const isLow = (entry: SignalEntry, atOrBelow: number): boolean =>
  entry.mood !== null &&
  entry.mood <= atOrBelow &&
  entry.sleep !== null &&
  entry.sleep <= atOrBelow

const requirePatternRule = (rules: DashboardRules): PatternRule => {
  const rule = rules.pattern
  if (!rule) throw new PatternRuleUnsetError()
  // Two ceilings, for two different reasons. `lowAtOrBelow` is a rating, and ratings are
  // whole numbers from 1 to 5, so `5` calls *every* answered rating low. The two day counts
  // are bounded above because the card's own sentences ("consecutive days", "the last few
  // days") stop being true of the number past 14: a larger count would be a rule that
  // matches a span no drawn copy describes (#178).
  const doses = [
    [
      'lowSignalDays',
      rule.lowSignalDays,
      14,
      "the card's copy says 'consecutive days' and 'the last few days', which stop being true past 14",
    ],
    [
      'lowAtOrBelow',
      rule.lowAtOrBelow,
      4,
      'ratings are whole numbers from 1 to 5, so 5 would call every answered rating low',
    ],
    [
      'severeSymptomDays',
      rule.severeSymptomDays,
      14,
      "the card's copy says 'consecutive days' and 'the last few days', which stop being true past 14",
    ],
  ] as const
  for (const [field, value, max, ceiling] of doses) {
    // A zero or a fraction would not be a quieter rule, it would be a rule that never
    // matches — indistinguishable, from the outside, from one that is switched off.
    if (!Number.isInteger(value) || value < 1) {
      throw new PatternRuleUnsetError(`${field} must be a positive integer`)
    }
    // And the mirror of that, which is the quieter failure: a rule that always matches
    // surfaces nothing and reads, from the card, as a pattern in her data. Refused for the
    // same reason as a zero.
    if (value > max) {
      throw new PatternRuleUnsetError(`${field} must be at most ${max}: ${ceiling}`)
    }
  }
  return rule
}

/**
 * Whether `mood_pattern` is true of her — which is the only question this may ask, because
 * it is the only pattern card `content/` has.
 *
 * **A32's severe-symptom arm is deliberately not here.** It used to fall into the same
 * `return`, so severe cramps three days running with mood 5 and sleep 5 selected a card
 * reading "You've logged low mood for three consecutive days". The card it needs is
 * `symptom_pattern`, which does not exist: writing it is D2's, not a rule this slice may
 * invent. Until it does, such a run falls through to `signals_today`. `severeSymptomDays`
 * stays validated so the day the card arrives, the dose behind it is already known good.
 *
 * **What that fallback says is not true of her either** (#177). This comment claimed it
 * "describes what she logged and claims nothing beyond it"; `signals_today`'s title names
 * low energy and a headache, and a severe-cramps run logged neither. Routing the run
 * somewhere whose copy nobody re-read is the same mistake one rung down, and it is recorded
 * as such in `api/test/dashboard-copy.test.ts` rather than argued about in a comment again.
 */
const matchesPattern = (input: DashboardInput, rule: PatternRule): boolean => {
  const lowRun = runEndingToday(input, rule.lowSignalDays)
  return lowRun !== null && lowRun.every((entry) => isLow(entry, rule.lowAtOrBelow))
}

// ── The ladder (PRD §Dashboard → Priority ladder) ──────────────────────────────────────

type LadderStep = (input: DashboardInput, rules: DashboardRules) => Subject | null

/**
 * Rung 1 — red-flag escalation. Always wins, and reaches the card without passing the model
 * at all (PRD §Calendar Other requirements 5). Deliberately evaluated before rung 2 asks for
 * its configuration and before any time input is parsed: an escalation must never fail to
 * appear because of a problem in a rung below it.
 *
 * **Every mode, because "always wins" has no mode in it.** The only flag template today is
 * `home_flag`, whose content `mode` is `pregnancy` — so a red flag raised in cycle mode
 * would name a pregnancy template. That cannot happen while `redFlag` is `null` everywhere,
 * which it is until D10 supplies the trigger mapping, and narrowing rung 1 to one mode here
 * would be this slice deciding D10's rule. Left as the seam it is, and now pinned by a test
 * that reads the template's own `mode` out of the seed rather than by one that only checks
 * a red flag wins.
 */
const redFlagRung: LadderStep = (input) =>
  input.redFlag === null
    ? null
    : {
        rung: 'flag',
        templateId: TEMPLATE.redFlag,
        slots: { loggedAt: input.redFlag.loggedAt },
        confidence: 'plain',
      }

/**
 * Rung 2 — what she reported, and the pattern in it.
 *
 * Three subjects share this rung, and the order among them is the one thing the PRD leaves
 * open. It is settled here on a single line: **the observed-data rule protects her log from
 * being contradicted**, not from being outranked. `home_d` says she is probably energetic,
 * so a log of low energy must beat it; `home_f` says her period is late, which contradicts
 * nothing she reported and is the more consequential thing to say, so it goes first. The
 * named pattern (A32) goes before both — it is the rung the PRD actually lists here, and it
 * is made of her own logs across days rather than one of them.
 *
 * **Two of the four are cycle-mode cards, and are gated as such** — the same gate rung 4
 * opens with, for the same reason. `late_period` and `signal_overrides_phase` are
 * `mode: 'cycle'` in `content/`, and a cycle estimate is still carried in the other modes:
 * without the gate, a user in loss mode two days past a predicted period was shown "Your
 * period is later than predicted", with *Log period* and *Log test* under it, days after a
 * pregnancy loss. `mood_pattern` and `signals_today` are `mode: 'any'` and stay mode-free:
 * each is *about* what she logged, which is as relevant in one mode as another — but note
 * that "about her log" is not the same as "true of her log", and `signals_today`'s words are
 * not (#177). The mode gate is right; the card behind it is the open half.
 */
const patternRung: LadderStep = (input, rules) => {
  const rule = requirePatternRule(rules)

  if (matchesPattern(input, rule)) {
    return { rung: 'pattern', templateId: TEMPLATE.moodPattern, slots: {}, confidence: 'plain' }
  }

  // A prediction only exists once C11's gates pass, so lateness needs no gate of its own —
  // beyond the two here. `> 0` because `0` is the predicted day *itself*: saying the period
  // is later than predicted on the day the calendar predicts contradicts the calendar, and
  // outranks what she actually logged to do it. `cycleDay` is required rather than assumed:
  // the card carries it, and this ladder never selects a template it cannot fill.
  if (
    input.mode === 'cycle' &&
    input.cycle.daysPastPredictedPeriod !== null &&
    input.cycle.daysPastPredictedPeriod > 0 &&
    input.cycle.cycleDay !== null
  ) {
    return {
      rung: 'pattern',
      templateId: TEMPLATE.latePeriod,
      slots: { cycleDay: input.cycle.cycleDay },
      confidence: 'plain',
    }
  }

  const observed = observedSignal(input)
  if (observed === null) return null

  // `home_e` reads her log *against* the phase, so it needs a phase it may speak — and a
  // mode whose card that phase belongs to. Without either — another mode, no cycle data,
  // too few cycles, irregular, or an estimate C11 withheld — the card responds to the
  // signals alone and never mentions a phase (`home_g`, canvas G).
  if (input.mode === 'cycle') {
    const phase = speakablePhase(input.cycle)
    if (phase !== null && input.cycle.cycleDay !== null) {
      return {
        rung: 'pattern',
        templateId: TEMPLATE.signalOverridesPhase,
        slots: { cycleDay: input.cycle.cycleDay },
        confidence: 'plain',
      }
    }
  }
  return { rung: 'pattern', templateId: TEMPLATE.signalsToday, slots: {}, confidence: 'plain' }
}

/**
 * Rung 3 — a mode milestone.
 *
 * **Inert in all five modes, not only in cycle mode.** Every milestone template in
 * `content/` is mode-specific (`home_preg`, `home_post`, `home_loss`) and belongs to D10;
 * cycle mode has none — but this step returns `null` unconditionally, so pregnancy does not
 * reach `home_preg` either, even though that card exists and the appointment input below is
 * already wired. Selecting one is D10's, together with the rest of the mode's ladder; what
 * this slice owns is the rung's place in the order, which is why the step is here at all.
 * An upcoming appointment is therefore not applicable rather than skipped, and inventing a
 * card for it would be writing copy in the rules layer.
 *
 * Whether cycle mode *should* have a milestone card is a content question for D2, not a
 * rule this slice may answer. Filed rather than fixed.
 */
const milestoneRung: LadderStep = () => null

/**
 * Rung 4 — cycle phase context, and the cold start that stands in for it.
 *
 * Only cycle mode is decided here. `home_plan`'s fertile-window variant is D10's, and a
 * pregnant or postpartum user reaching this rung falls through to the educational fallback
 * rather than being shown a cycle card, which is the safe direction to fail. Within cycle
 * mode the phase card is follicular-only, and a speakable phase that is not falls through the
 * same way — the comment at that branch says why, and what it costs (#184).
 */
const phaseRung: LadderStep = (input) => {
  if (input.mode !== 'cycle') return null

  // PRD Edge case 1 — "No data at all (first open after Sign Up)… No phase, no prediction,
  // no generic tip dressed as insight." Nothing logged is the whole predicate: this must not
  // fire for someone who has data the card simply cannot speak about yet.
  if (input.daysSinceLastLog === null && input.cycle.cycleDay === null) {
    return { rung: 'setup', templateId: TEMPLATE.coldStart, slots: {}, confidence: 'plain' }
  }

  // **`phase_energy` is selected for the follicular phase only, and that is a narrowing, not an
  // oversight (#184).** Its words are fixed — "likely approaching ovulation" over "Many women
  // notice higher energy around now" — and it used to be selected for every speakable phase,
  // so a woman on cycle day 2 or day 21 read a kicker naming the wrong phase over a title
  // asserting the opposite of the tendency. The phase is not chosen by reading the copy here:
  // `api/test/dashboard-copy.test.ts` holds each line to a claim, and this is the one phase
  // every line is true of — the kicker holds for follicular alone, the title for follicular or
  // ovulation. Ovulation is the tempting widening, and it is wrong: C11's `ovulation` is the
  // whole fertile window, which runs past ovulation day, and the code cannot say which part of
  // it today is.
  //
  // **This is #175's decision, one rung down** — there it narrowed rung 2's pattern predicate
  // to the words of the one pattern card rather than write a sentence the canvas had not drawn.
  // The gap here is the same and it is the canvas's: `home_d` has only ever been drawn for the
  // approach to ovulation, and no per-phase variant exists. The rung widens when a variant is
  // drawn, seeded and audited, one phase at a time — never by adding a phase to this line,
  // which the audit reports as a mismatch it has no row for, and fails on, as it should.
  //
  // **The cost, stated plainly:** the card fires on a few days of each cycle, and every other
  // day falls through to the educational card, so most users will see that card on most days
  // until the canvas draws the variants. That is a worse product and a correct one. A card that
  // is true on the few days it fires beats one that fires every day and is false on most.
  const phase = speakablePhase(input.cycle)
  if (phase !== null && phase.code === 'follicular' && input.cycle.cycleDay !== null) {
    return {
      rung: 'phase',
      templateId: TEMPLATE.phaseEnergy,
      slots: { cycleDay: input.cycle.cycleDay, phase: phase.code },
      confidence: PHASE_WORDING[phase.confidence],
    }
  }

  // There is cycle data, but not enough of it to speak from. Both cards say so and neither
  // carries a phase — PRD Confidence and cold start 2 and 3. Too-few-cycles is asked first:
  // below the gate there are not enough cycles to call variation irregular in the first
  // place, so "still learning" is the honest answer even when the flag happens to be set.
  if (input.cycle.cycleDay !== null) {
    if (!input.cycle.enoughCyclesForEstimates) {
      return {
        rung: 'phase',
        templateId: TEMPLATE.stillLearning,
        slots: { cycleCount: input.cycle.countedCycles },
        confidence: 'hedged',
      }
    }
    // **`irregular` is selected for `cycles-vary` alone, and that is a narrowing rather than
    // an oversight (#190)** — the same decision #184 made one card along, for the same
    // reason. `home_c`'s line reads "Your recent cycle lengths vary significantly", and for
    // a woman whose counted cycles are all 28 days and who missed one period start, that
    // sentence is false: what Eva has is one interval it could not read. She was shown it
    // for six cycles, because the mislogged interval keeps closing the band until six
    // further counted cycles push it out of the window.
    //
    // The prediction and the phase are still withheld — the gate is C11's and this changes
    // none of it (#181's fail-closed path is untouched, and `speakablePhase` above suppresses
    // on any reason). What changes is that she is no longer *told* something about her body
    // that her data does not support, which is what puts this in the same class as the
    // fourteen strings `api/test/dashboard-copy.test.ts` enumerates.
    //
    // **The cost, stated plainly:** `uncountable-cycle` reaches no phase card at all and
    // falls through to the educational one, so she is given no explanation on the Today card
    // where she used to be given a wrong one. The card that would explain it — "Eva cannot
    // read one of your recent cycles" — is a sentence the canvas has not drawn, and #177's
    // rule is that where the canvas has not drawn a card the honest output is a request, not
    // an invention in the seed. The reason itself is not lost: it reaches the calendar as
    // C11's `uncountable-cycle` on `GET /me/cycle/predictions`, which is where a woman asks
    // why there is no overlay.
    if (input.cycle.irregularity === 'cycles-vary') {
      return { rung: 'phase', templateId: TEMPLATE.irregular, slots: {}, confidence: 'hedged' }
    }
  }

  return null
}

/**
 * Rung 5 — a nutrition or training suggestion from her goal and today's totals.
 *
 * `content/` carries **no rung-5 template**: D2 seeded the fourteen the canvas draws and
 * none of them is this rung. So this rung has nothing to select, and says so here rather
 * than by being absent from the ladder — the ladder's order is the specification, and a
 * missing step reads as a decision nobody made. Its inputs (`nutritionSetUp`,
 * `todayTotals`, `profileComplete`) are declared above so the rule lands here when the copy
 * exists, and so the gate is already written down: no suggestion without the setup and the
 * profile behind it (PRD Confidence and cold start 4).
 */
const nutritionRung: LadderStep = () => null

/**
 * Rung 6 — the fallback, and the reason the ladder cannot come up empty.
 *
 * Labelled as a read, not as insight (canvas: "Educational fallback is clearly labeled
 * 'Today's read' so it is never mistaken for personal insight").
 *
 * Its `category` and `readMinutes` slots describe **the article**, and no slice owns picking
 * one: D1 chooses a subject, D3 fills a template, D7 is the banner rail. They are therefore
 * left unfilled rather than guessed at, and the content-store case pins exactly which two
 * are missing so this stops being invisible the moment someone claims the card is complete.
 */
const educationRung = (): Subject => ({
  rung: 'education',
  templateId: TEMPLATE.educational,
  slots: {},
  confidence: 'plain',
})

/** The PRD's ladder, in the PRD's order. Rung 6 is applied after this list because it
 *  always applies — see `educationRung`. */
const LADDER: readonly LadderStep[] = [
  redFlagRung,
  patternRung,
  milestoneRung,
  phaseRung,
  nutritionRung,
]

/**
 * Choose the day's subject. **First applicable rung wins and nothing else is shown**
 * (PRD §Priority ladder, and Edge case 4 for the day several rungs apply at once).
 *
 * Throws `PatternRuleUnsetError` if the ladder reaches rung 2 without a configured rule,
 * and `InvalidTimeError` if `today`, `now` or a `loggedAt` is not the shape documented on
 * the input. Both are refusals rather than failures: answering past either would produce a
 * card that looks live and is not. Both are also *lazy*, so rung 1 still answers — an
 * escalation must not be suppressed by a problem in a rung below it.
 */
export const selectSubject = (input: DashboardInput, rules: DashboardRules): Subject => {
  for (const rung of LADDER) {
    const subject = rung(input, rules)
    if (subject !== null) return subject
  }
  return educationRung()
}
